# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-22 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='date',
        ),
        migrations.AddField(
            model_name='test',
            name='salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
