# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-23 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmplyee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('emailId', models.EmailField(max_length=120)),
                ('mobileNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
