# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-23 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagementPortal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddEmplyee',
            new_name='AddEmployee',
        ),
    ]
